// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwnbnvZf-4WQouqyHv-EY9AOAenAtUZWs',
    appId: '1:892176384276:web:22cac62c09f1c20ee74201',
    messagingSenderId: '892176384276',
    projectId: 'insatstore',
    authDomain: 'insatstore.firebaseapp.com',
    storageBucket: 'insatstore.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwc8UtP1HvmAHQkwdL4OJEAlyd30OexO0',
    appId: '1:892176384276:android:ce994e7f1c22f07ae74201',
    messagingSenderId: '892176384276',
    projectId: 'insatstore',
    storageBucket: 'insatstore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Vy07OibOMa19NYZlkLlzvOuHPflj6RU',
    appId: '1:892176384276:ios:27542b7b93685c10e74201',
    messagingSenderId: '892176384276',
    projectId: 'insatstore',
    storageBucket: 'insatstore.firebasestorage.app',
    iosBundleId: 'com.example.tp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3Vy07OibOMa19NYZlkLlzvOuHPflj6RU',
    appId: '1:892176384276:ios:27542b7b93685c10e74201',
    messagingSenderId: '892176384276',
    projectId: 'insatstore',
    storageBucket: 'insatstore.firebasestorage.app',
    iosBundleId: 'com.example.tp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwnbnvZf-4WQouqyHv-EY9AOAenAtUZWs',
    appId: '1:892176384276:web:7d18ee4eb187e606e74201',
    messagingSenderId: '892176384276',
    projectId: 'insatstore',
    authDomain: 'insatstore.firebaseapp.com',
    storageBucket: 'insatstore.firebasestorage.app',
  );

}